### PR TITLE
Upgrade to GameFinder 3

### PR DESCRIPTION
**Pull request by erri120**

### CODE REVIEW

**Comment by bcssov** [comment]
Thanks

**Comment by bcssov** [comment]
Sorry, going to have to revert this as the build fails. Using strongnamer I currently don't have time do dig deeper.
```Failed to write signed assembly to 'D:\Working\IronyModManager\src\IronyModManager.Services\obj\x64\Debug\net7.0\SignedAssemblies\NexusMods.Paths.dll'. Mono.Cecil.ResolutionException: Failed to resolve System.IO.FileAccess```

**Comment by bcssov** [comment]
Here's a repro for you.

[ConsoleApp1.zip](https://github.com/bcssov/IronyModManager/files/11454605/ConsoleApp1.zip)

```
1>Failed to write signed assembly to '\net7.0\SignedAssemblies\NexusMods.Paths.dll'. Mono.Cecil.ResolutionException: Failed to resolve System.IO.FileAccess
1>   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
1>   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
1>   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
1>   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table)
1>   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method)
1>   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
1>   at Mono.Cecil.MetadataBuilder.AddTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildTypes()
1>   at Mono.Cecil.MetadataBuilder.BuildModule()
1>   at Mono.Cecil.MetadataBuilder.BuildMetadata()
1>   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _)
1>   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
1>   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
1>   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
1>   at StrongNamer.AddStrongName.ProcessAssembly(ITaskItem assemblyItem, Byte[] keyBytes, StrongNamerAssemblyResolver resolver)
1>CSC : error CS0006: Metadata file 'net7.0\SignedAssemblies\NexusMods.Paths.dll' could not be found
```

**Comment by erri120** [comment]
Just out of curiosity, why are you using strong-named assemblies? The MS docs say it's basically useless in .NET Core and .NET 5+: https://learn.microsoft.com/en-us/dotnet/standard/assembly/strong-named

**Comment by bcssov** [comment]
There are still benefits. But the reason why it was used was as a placeholder; as a part of a better future security to prevent the program to load non validated binaries. Community feedback and general project direction lead elsewhere. Program loads dynamically some assemblies (and validates them) with theoretical plugin support so at the very least I wanted some rudimentary validation.

**Comment by bcssov** [comment]
I too can build if I invoke `dotnet build`. And then subsequently build from within visual studio. But the problem is on a clean solution and build within VS 2022 (that's not very convenient for me). 

Feel free to close the issue on your end, thanks for looking into it.

**Comment by erri120** [comment]
> I too can build if I invoke `dotnet build`. And then subsequently build from within visual studio. But the problem is on a clean solution and build within VS 2022 (that's not very convenient for me).
> 
> Feel free to close the issue on your end, thanks for looking into it.

That's a VS issue. JetBrains Rider works fine, even on clean builds.

**Comment by bcssov** [comment]
Most likely yeah, which is why I said you can close the ticket on your end. 

For me this is still a show stopper, maybe in the future if the issue is resolved by the VS team I'll look into it once again.

**Pull request merged**
