### PR TITLE
Add zh lang

### PR DESCRIPTION
**Pull request by Windmill-City**

### CODE REVIEW

**Comment by bcssov** [comment]
Oh, hello there. 

Wish you contacted me before you started doing this, it must have been a pain to setup the project especially due to a missing nuget for you (CWTools private build that I have -- since the regular nuget is not updated frequently. And I gave up on expecting contributions :).

Anyway, before I proceed I'd just like to ask did you notice any rendering issues in your translation? I am aware of several issues with existing fonts that avalonia uses that have rendering issues of chinese\korean\japanese fonts. If so, I'm open to doing changes like allowing you to specify a custom font or perhaps embedding a font (if that's even possible in Avalonia) for your use case.

**Comment by Windmill-City** [comment]
I didnt see any rendering issues

**Comment by Windmill-City** [comment]
do you mean #50 ?, I've tested around and all the char display correctly, maybe it is your English Version OS cause the bug

**Comment by Windmill-City** [comment]
image
the chars are fine

**Comment by bcssov** [comment]
That is fantastic, given your feedback I'll then close the ticket you mentioned. I know for me it does not render (probably as I'm missing some fonts). 

For me for example it rendered like this:
https://user-images.githubusercontent.com/7077098/76654485-6d583b80-6541-11ea-9906-f28d9236d6e0.png

Know tickets I kept around on avalonia: https://pastebin.com/pBfjqQv8

**Comment by bcssov** [comment]
I'm going to accept this PR but changes will be available in 1.7. I need to resolve issues for us westerners due to rendering issues I mentioned. We only see boxes rendering.

**Pull request merged**
